LKG4Manager/
    VisMode 0
    NPToolMode true
    G4OutputFile ./data/mc_0001.root
    #G4OutputFile mc_direct_000.root
    SetAutoUpdateCopyNo false
    SuppressG4InitMessage true

NPTool/
    ReactionFile Ne20_3alpha.reaction
    #ReactionFile fusion.reaction
    #ReactionFile SingleAlpha2.reaction
    #ReactionFile SourceTestAlpha.reaction
TPCDrum/
    GasPressure 760. #asasdf [torr]
    GasContourMixRatio 10. # [%] for contour gas
    WindowMaterial Havar # [Havar, etc..]
    WindowThickness 0.01 # [mm]
    GatingGrid true
    PeakingTime 502
    TBUnit 20

persistency/
    MCTrackVertex true
    MCSecondary true
    MCEdepSum false
    MCStep true

G4/
    #gun/partile alpha
    #gun/energy 40MeV
    #gun/position 0 0 -330 mm
    #gun/direction 0 0 1
    vis/open OGL 600x600-0+0
    vis/drawVolume
    vis/scene/add/axes 0 0 0 10 cm
    vis/viewer/flush
    vis/viewer/set/lightsVector -1 0 0
    vis/viewer/set/style surface
    vis/viewer/set/auxiliaryEdge true
    vis/viewer/set/lineSegmentsPerCircle 100
    vis/scene/add/trajectories smooth
    vis/modeling/trajectories/create/drawByCharge
    vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
    vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
    vis/scene/endOfEventAction accumulate 10
    vis/geometry/set/visibility World 0 false
    vis/viewer/set/viewpointThetaPhi 100 160
    vis/viewer/set/autoRefresh true
    tracking/verbose 0
    vis/verbose warnings
    run/setCutForAGivenParticle e- 100. mm
    run/beamOn 10000
