# example.mac created from LKParameterContainer::Print

LKRun/Name                    run                  # --> run # name of the run
LKRun/RunID                   0                    # --> 0 # run number
LKRun/Tag                     tag                  # --> tag # tag
LKRun/OutputPath              {lilak_data}         # --> /home/ejungwoo/lilak/data # path to the output. Default path {lilak_data} is lilak/data/
#LKRun/InputPath               /path/to/in/         # --> /path/to/in/ # LKRun will search files from input paths when LKRun/SearchRun
LKRun/SearchRun               mfm                  # --> mfm # search input files with LKRun/RunID. opt=mfm: search mfm files, opt=[tag]: search run_runNo.*.[tag].root
#LKRun/Division                0                    # --> 0 # division within the run [optional]
LKRun/InputFile               to/input/file        # --> to/input/file # input file. Cannot be used with LKRun/SearchRun
#LKRun/FriendFile              to/friend/file       # --> to/friend/file # input friend file
#LKRun/RunIDList               1, 2, 3, 4           # --> 1, 2, 3, 4 # list of run numbers separated by ,
#LKRun/RunIDRange              1, 10                # --> 1, 10 # list of run numbers ranged by ,
#LKRun/EntriesLimit            100000               # --> 100000 # limit number of run entries
LKRun/EventCountForMessage    20000                # --> 20000 # 
LKRun/AutoTerminate           true                 # --> true # automatically terminate root after end of run
LKRun/MainName                                     # -->  # 
LKRun/UpdateOutputFile                             # -->  # 

#LKEveTask/selectTrackIDs      0                    # --> 0 # 
#LKEveTask/ignoreTrackIDs      0                    # --> 0 # 
#LKEveTask/selectTrackParentIDs                    0                    # --> 0 # 
#LKEveTask/ignoreTrackParentIDs                    0                    # --> 0 # 
#LKEveTask/selectTrackPDGs     0                    # --> 0 # 
#LKEveTask/ignoreTrackPDGs     0                    # --> 0 # 
#LKEveTask/selectMCIDs         0                    # --> 0 # 
#LKEveTask/ignoreMCIDs         0                    # --> 0 # 
#LKEveTask/selectHitParentIDs  0                    # --> 0 # 
#LKEveTask/ignoreHitParentIDs  0                    # --> 0 # 
#LKEveTask/selectBranches      0                    # --> 0 # 
#LKEveTask/drawEve3D           false                # --> false # draw 3d event display using ROOT EVE package and root geometry defined in detector class
#LKEveTask/drawPlane           true                 # --> true # draw 2d planes using detector plane class

LKHTTrackingTask/hit_branch   Hit                  # --> Hit # branch name containing LKHit
LKHTTrackingTask/binning_x    100, -100, 100       # --> 100, -100, 100 # x-axis binning for hough transform image space
LKHTTrackingTask/binning_y    100, -100, 100       # --> 100, -100, 100 # y-axis binning for hough transform image space
LKHTTrackingTask/transform_ct 0, 0, 0              # --> 0, 0, 0 # transform center, is center point where transform is performed.
LKHTTrackingTask/binning_t    100, 0, 0            # --> 100, 0, 0 # range 0, 0 will set range automatically
LKHTTrackingTask/num_hits_cut 3                    # --> 3 # Skip event if number of hits in event is lower than this cut
LKHTTrackingTask/mode         xy, zy               # --> xy, zy # Choose from xy, yz, yz, yx, zx, zy. If two different modes are selected, two HT-trackers will be created
LKHTTrackingTask/binning_z    100, -100, 100       # --> 100, -100, 100 # z-axis binning for hough transform image space
LKHTTrackingTask/binning_r    100, 0, 0            # --> 100, 0, 0 # range 0, 0 will set range automatically

#[BranchName]/lineStyle        1                    # --> 1 # track line style of [BranchName].
#[BranchName]/lineWidth        1                    # --> 1 # track line width of [BranchName].
#[BranchName]/lineColor        kBlack               # --> 1 # track line color of [BranchName].
#[BranchName]/markerStyle      20                   # --> 20 # track marker style of [BranchName].
#[BranchName]/markerSize       1                    # --> 1 # track marker size  of [BranchName].
#[BranchName]/markerColor      kBlue                # --> 600 # track marker style of [BranchName].

#lilak/add                     LKTask               # --> LKTask # add task or detector class
#lilak/print                   all                  # --> all # print after init gen:par:out:in:det:task
#lilak/collect_par             print                # --> print # file name to write collected parameters. 'print' to print out on screen
#lilak/run                     0                    # --> 0 # run [no] after init. Execute all events if [no] is 0
#lilak/draw                    0                    # --> 0 # execute Draw()
#lilak/execute                 0                    # --> 0 # execute event [no] after init

persistency/Hit               true                 # --> true # 
persistency/Track             true                 # --> true # 
